/*
####  Amplify the Multiples of Four  ####

Create a function that takes an integer and returns an array from 1 to the given number, where:



[Examples]

___
amplify(4) ➞ [1, 2, 3, 40]

amplify(3) ➞ [1, 2, 3]

amplify(25) ➞ [1, 2, 3, 40, 5, 6, 7, 80, 9, 10, 11, 120, 13, 14, 15, 160, 17, 18, 19, 200, 21, 22, 23, 240, 25]
_____



[Notes]

___
*) The given integer will always be equal to or greater than 1.
*) Include the number (see example above).
___



[algebra] [arrays] [loops] [math] 



-------------------------------------------------------------------
[Resources]
_________
vector::push_back() and vector::pop_back()
https://www.geeksforgeeks.org/vectorpush_back-vectorpop_back-c-stl/#:~:text=Vectors%20are%20same%20as%20dynamic,handled%20automatically%20by%20the%20container.&text=push_back()%20function%20is%20used,a%20vector%20from%20the%20back.
Vectors are same as dynamic arrays with the ability to resize itself automatically when an element is inserted or deleted, with their storage being handled automaticall …
_________
_________
vector::push_back
http://www.cplusplus.com/reference/vector/vector/push_back/
Adds a new element at the end of the vector, after its current last element. The content of val is copied (or moved) to the new element. This effectively increases the …
_________
_________
std::generate_n
https://en.cppreference.com/w/cpp/algorithm/generate_n
Assigns values, generated by given function object g, to the first count elements in the range beginning at first, if count>0. Does nothing otherwise.
_________
_________
std::vector<T,Allocator>::resize
https://en.cppreference.com/w/cpp/container/vector/resize
Resizes the container to contain count elements.
_________
_________
std::generate
http://www.cplusplus.com/reference/algorithm/generate/?kw=generate
Assigns the value returned by successive calls to gen to the elements in the range [first,last).
_________

*/
//Your code should go here:

