/*
####  Find the Difference  ####

You are given two strings s and t.
String t is generated by randomly shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.


[Examples]

___
findTheDifference("bcefg", "bcdefg") ➞ 'd'

findTheDifference("abcd", "abcde") ➞ 'e'

findTheDifference("aiou", "aeiou") ➞ 'e'

findTheDifference("mnoqrst", "mnopqrst") ➞ 'p'
_____



[Notes]

N/A


[algorithms] [strings] 



-------------------------------------------------------------------
[Resources]


[No Resources]


*/
//Your code should go here:

