"""
####  Coloured Triangles  ####

A coloured triangle is created from different rows of colours (Red, Green or Blue). Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If colours are different, the missing colour is used in the new row. This process continues untill a single colour is generated in the final row.
Different possibilities of colours are:
___
Colours Touching:        G G        B G        R G        B R
New colour:               G          R          B          G
_____

With a bigger example:
___
R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
_____



[Goal]

___
*) Create a function which takes first row of the triangle as an input and returns the final colour which would appear at the bottom row. In above example, given input "RRGBRGBB" will return "G".
*) If you are only given one colour as the input, return that colour.
*) There will be no exception handling case.
___



[Examples]

___
coloured_triangle("B") ➞ "B"

coloured_triangle("GB") ➞ "R"

coloured_triangle("RBRGBRB") ➞ "G"
_____



[Notes]

N/A


[games] [language_fundamentals] [strings] 



-------------------------------------------------------------------
[Resources]
_________
zip() Function
https://www.w3schools.com/python/ref_func_zip.asp
Returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator a …
_________
_________
difference() Function
https://www.geeksforgeeks.org/python-set-difference/
The difference between the two sets in Python is equal to the difference between the number of elements in two sets. The function difference() returns a set that is the …
_________

"""
#Your code should go here:

