"""
####  Find the Difference  ####

You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.


[Examples]

___
find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"
_____



[Notes]

N/A


[algorithms] [strings] 



-------------------------------------------------------------------
[Resources]
_________
Python String replace()
https://www.programiz.com/python-programming/methods/string/replace
Returns a copy of the string where all occurrences of a substring is replaced with another substring.
_________
_________
chr() and ord()
https://www.askpython.com/python/built-in-methods/python-chr-and-ord-methods
In this lesson, we'll work with the python chr() and ord() functions. Python’s built in function chr() is used for converting an Integer to a Character, while ...
_________
_________
Counter — Count Hashable Objects
https://pymotw.com/3/collections/counter.html
A Counter is a container that keeps track of how many times equivalent values are added. It can be used to implement the same algorithms for which other languages comm …
_________
_________
Learn by Example – '.count' Function
https://www.learnbyexample.org/python-string-count-method/
A guide from the website 'Learn by Example' on the '.count' Function which enables a user to establish the number of instances that a specified parameter appears within …
_________
_________
Lists
https://www.w3schools.com/python/python_lists.asp
Are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.
_________

"""
#Your code should go here:

