/*
####  Get the Lucky Number  ####

A lucky number is a number of a sequence generated by a sieve algorithm: if a number in the positive integers series survives to the sieve filtering algorithm, it's lucky and survives, otherwise it disappears from the sequence.
___
*) First you must obtain an array of numbers, from 1 to the needed size.
*) First number is 1 and it survives: next to him there is number 2, that becomes the sieve's filter: every second number in the list (counting from 1) has to be filtered (as to say every even number).
*) After this step, the next number to survive after 1 is 3: eliminate every third number in the list (counting from 1).
*) After this step, the next number to survive after 3 is 7: eliminate every seventh number in the list.
*) Repeat the steps incrementing the filter condition at every step (as to say that the sieve filter of a new step is equal to the first number greater than the previous step last lucky number) until there are no numbers to eliminate in the list.
___

See the example below for a given size = 25 and nth = 5.
___
*) Step 1: Generate a list from 1 to size.

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25
*) Step 2: First sieve filter is 2: every second number from the start has to be eliminated.

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25
*) Step 3: Sieve filter is now 3: every third number from the start has to be eliminated.

1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25
*) Step 4: Sieve filter is now 7: every seventh number from the start has to be eliminated.

1, 3, 7, 9, 13, 15, 19, 21, 25
*) Step 5: Sieve filter is now 9: every ninth number has to be eliminated, but our list now contains only 8 numbers and so the algorithm ends. The nth number of the sequence is 13.
___

In the animation below, you can see the progressive sieving process for a list of 120 numbers: purple filling is for eliminated numbers, red is for lucky ones.

Given a size being the dimension of the starting array, write a function that returns the nth number of the resulting sequence after the sieving process.


[Examples]

___
getLuckyNumber(25, 5) ➞ 13
// Same set and procedure as in example in above instructions.

getLuckyNumber(3, 2) ➞ 3
// Original set = 1, 2, 3
// After first step = 1, 3
// No more steps possibles (filter is for every third element, length of set is 2)
// The second (nth) element is 3

getLuckyNumber(120, 13) ➞ 49
// Same set as in animated gif in above instructions.
_____



[Notes]

___
*) Check Resources tab for more info on lucky numbers.
*) Every given size and nth are valid parameters to return a lucky number, there are no exceptions to handle.
*) Despite this sieve has similarities with the "Sieve of Eratosthenes" used for retrieving prime numbers in the ancient Greece, it is more related to the ancient Josephus permutations challenge (as in this exercise or this one): is it in fact usually called "The Josephus Flavius Sieve".
___



[algorithms] [math] [numbers] 



-------------------------------------------------------------------
[Resources]
_________
List
https://www.geeksforgeeks.org/list-interface-java-examples/
The List interface in Java provides a way to store the ordered collection. It is a child interface of Collection. It is an ordered collection of objects in which duplic …
_________
_________
While Loop
https://www.geeksforgeeks.org/java-while-loop-with-examples/
Is a control flow statement that allows code to be executed repeatedly based on a given Boolean condition. The while loop can be thought of as a repeating if statement. …
_________
_________
Lucky Numbers
https://www.geeksforgeeks.org/lucky-numbers/
Before every iteration, if we calculate position of the given no, then in a given iteration, we can determine if the no will be deleted. Suppose calculated position for …
_________
_________
Lucky Number
https://en.wikipedia.org/wiki/Lucky_number
A natural number in a set which is generated by a certain "sieve". This sieve is similar to the Sieve of Eratosthenes that generates the primes, but it eliminates numbe …
_________

*/
//Your code should go here:

